### ISSUE TITLE
Lint could not load custom rule jar with android gradle plugin v2.3.3

### ISSUE THREAD

**Issue by OsipXD** [permissions-dispatcher/PermissionsDispatcher#392]
## Overview

- Can't build project after add PermissionDispatcher

### Expected

- Project building should be successful

### Actual

- I have error that looks like conflict with lint and crashes my build
```java
Could not load custom rule jar file /home/user/.android/build-cache/317bbf7182688f2c4e85a24d078fe2ab62ffb2a0/output/jars/lint.jar
java.lang.NoClassDefFoundError: com/android/tools/lint/detector/api/Detector$UastScanner
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at permissions.dispatcher.PermissionsDispatcherIssueRegistry.getIssues(PermissionsDispatcherIssueRegistry.java:13)
	at com.android.tools.lint.client.api.JarFileIssueRegistry.<init>(JarFileIssueRegistry.java:125)
	at com.android.tools.lint.client.api.JarFileIssueRegistry.get(JarFileIssueRegistry.java:90)
	at com.android.tools.lint.client.api.LintDriver.registerCustomDetectors(LintDriver.java:603)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:521)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:483)
	at com.android.tools.lint.LintCliClient.run(LintCliClient.java:143)
	at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:197)
	at com.android.build.gradle.tasks.Lint.runLint(Lint.java:340)
	at com.android.build.gradle.tasks.Lint.lintAllVariants(Lint.java:140)
	at com.android.build.gradle.tasks.Lint.lint(Lint.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.android.tools.lint.detector.api.Detector$UastScanner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 69 more
```

## Environment

- Kotlin 1.1.51
- PremissionDispatcher 3.0.1
- Lint 25.3.3

## Reproducible steps

Project with this issue: https://github.com/OsipXD/bb-test-task

**Comment by OsipXD** [comment]
I've changed version of Android Gradle Plugin from 2.3.3 to 3.0.0-beta9 and problem disappeared.
Please make it compatible with 2.3.3

**Comment by mannodermaus** [comment]
UAST has been a quite recent development, and its adoption hasn't been made until somewhere in the AGP 3.x lifeline, which is why previous versions of the plugin fail. A simple try-catch would do here, however then we would lose Lint on 2.x plugin setups... @hotchemi @shiraji what do you think?

**Comment by shiraji** [comment]
UAST may be too early to use it. I think the advantage of using this version is for kotlin, right? And the lint 3.0 does not support it (#373) I don't like this but we need to revert the change since lint is one of big features for this library.

**Comment by hotchemi** [comment]
Thx guys.
Unfortunately if we reverted lint rules to before UAST we would face [the same problem](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/331) again and we'll not be able to provide Kotlin support because of [the issue](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/350)...Umm...I'm kinda stack...

@OsipXD Let me clarify, are you using Kotlin? If not you can use 2.x ver for the time being.

**Comment by mannodermaus** [comment]
We can also pull in the old Lint checks in addition to the UAST-based ones, and fall back to them in case UAST is absent.

Quick 7 a.m. draft:

```java
public final class PermissionsDispatcherIssueRegistry extends IssueRegistry {

    private static final List<Issue> UAST_ISSUES = Arrays.asList(
                CallNeedsPermissionDetector.ISSUE,
                CallOnRequestPermissionsResultDetector.ISSUE,
                NoCorrespondingNeedsPermissionDetector.ISSUE);

    private static final List<Issue> LEGACY_ISSUES = Arrays.asList(
                OldCallNeedsPermissionDetector.ISSUE,
                OldCallOnRequestPermissionsResultDetector.ISSUE,
                OldNoCorrespondingNeedsPermissionDetector.ISSUE);

    @Override
    public List<Issue> getIssues() {
    	return isUastAvailable()
    		? UAST_ISSUES
    		: LEGACY_ISSUES;
    }

    private boolean isUastAvailable() {
    	try {
            // Cache-able
            Class.forName("com.android.tools.lint.detector.api.Detector$UastScanner");
            return true;
        } catch (Throwable ignored) {
            return false;
        }
    }
}
```

**Comment by hotchemi** [comment]
OMG...LGTM 😂

**Comment by mannodermaus** [comment]
@OsipXD This should be an issue with any library that utilizes custom Lint rules built with UAST… by any chance, do you use [Timber](https://github.com/JakeWharton/timber) in your project, too? I'd expect the same behaviour to be present there, too, since there is no fallback to previous implementations as well in that library.

**Comment by mannodermaus** [comment]
First draft of the combined & re-architected Lint structure raised in #393

**Comment by OsipXD** [comment]
@hotchemi, yes I use Kotlin
@mannodermaus, no, I haven't Timber. I use these libs. Here project which have this issue: https://github.com/OsipXD/bb-test-task

**Comment by mannodermaus** [comment]
Thank you so much for linking to the project! We'll verify the behaviour momentarily. Theoretically though, any library with custom Lint rules built on UAST will trigger this problem.

**Comment by tim4dev** [comment]
I have the same problem.

**Comment by hotchemi** [comment]
We'll release minor update after https://github.com/permissions-dispatcher/PermissionsDispatcher/pulls being merged.

**Comment by hotchemi** [comment]
Now AS 3.0 became stable so let me close the issue!
