### ISSUE TITLE
hongyang`s Autolayout lib  is not work when use this permission lib

### ISSUE THREAD

**Issue by newbieandroid** [permissions-dispatcher/PermissionsDispatcher#399]
if use this permission lib ,the result is not to find hongyang`s  autolayout.
i think the reason is annotations ,but i can not find why

=========================The Log Info=====================
FATAL EXCEPTION: main
                                                              Process: com.app.base, PID: 18529
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.base/com.app.base.ui.MainActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class LinearLayout
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5523)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                               Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class LinearLayout
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                  at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
                                                                  at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
                                                                  at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:374)
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                  at com.app.base.base.BaseActivity.onCreate(BaseActivity.kt:23)
                                                                  at android.app.Activity.performCreate(Activity.java:6303)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                               Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class LinearLayout
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:786)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909) 
                                                                  at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981) 
                                                                  at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:374) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                  at com.app.base.base.BaseActivity.onCreate(BaseActivity.kt:23) 
                                                                  at android.app.Activity.performCreate(Activity.java:6303) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                  at com.zhy.autolayout.config.AutoLayoutConifg.getMetaData(AutoLayoutConifg.java:98)
                                                                  at com.zhy.autolayout.config.AutoLayoutConifg.init(AutoLayoutConifg.java:80)
                                                                  at com.zhy.autolayout.utils.AutoLayoutHelper.initAutoLayoutConfig(AutoLayoutHelper.java:111)
                                                                  at com.zhy.autolayout.utils.AutoLayoutHelper.<init>(AutoLayoutHelper.java:103)
                                                                  at com.zhy.autolayout.AutoLinearLayout.<init>(AutoLinearLayout.java:18)
                                                                  at com.zhy.autolayout.AutoLayoutActivity.onCreateView(AutoLayoutActivity.java:31)
                                                                  at android.app.Activity.onCreateView(Activity.java:5605)
                                                                  at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
                                                                  at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:758)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909) 
                                                                  at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981) 
                                                                  at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:374) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                  at com.app.base.base.BaseActivity.onCreate(BaseActivity.kt:23) 
                                                                  at android.app.Activity.performCreate(Activity.java:6303) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by hotchemi** [comment]
seems it's not related to our lib. @newbieandroid please ask to the lib author.

**Comment by newbieandroid** [comment]
oh,sorry.
it is not this permission lib fault,because my careless.
i find why lead this error and i fix it.
by the way,your lib is good,thanks
