### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by Wangct23** [permissions-dispatcher/PermissionsDispatcher#471]
V3.2.0
Android 5.1.1
When implement in DialogFragment : 

java.lang.ClassCastException: xxx.xxx.xxx.DialogFragment cannot be cast to android.support.v13.app.FragmentCompat$OnRequestPermissionsResultCallback
        at android.support.v13.app.FragmentCompat$FragmentCompatBaseImpl$1.run(FragmentCompat.java:100)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)

**Comment by hotchemi** [comment]
@Wangct23 We don't provide any DialogFragment related API so please check your code again? Or give us more detail.

**Comment by mannodermaus** [comment]
Hm, but since `DialogFragment` is also a `Fragment`, shouldn't this still work? I mean, still do provide more detail for us to work with, but that's potentially an interesting case.
