### ISSUE TITLE
Xiaomi crash java.lang.SecurityException SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by francescobonni** [permissions-dispatcher/PermissionsDispatcher#505]
Crash on `myMethodWithPermissionCheck()` when use `@NeedsPermission(Manifest.permission.SYSTEM_ALERT_WINDOW)`

Library version : 3.3.1 with kapt processor
Devices affected : Only Xiaomi Mi A1
Stacktrace: 

```java
Fatal Exception: java.lang.SecurityException: com.obscience.imamma from uid 10012 not allowed to perform SYSTEM_ALERT_WINDOW
       at android.app.AppOpsManager.noteOp(AppOpsManager.java:1837)
       at android.app.AppOpsManager.noteOp(AppOpsManager.java:1654)
       at android.support.v4.app.AppOpsManagerCompat.noteOp(AppOpsManagerCompat.java:106)
       at permissions.dispatcher.PermissionUtils.hasSelfPermissionForXiaomi(PermissionUtils.java:111)
       at permissions.dispatcher.PermissionUtils.hasSelfPermission(PermissionUtils.java:96)
       at permissions.dispatcher.PermissionUtils.hasSelfPermissions(PermissionUtils.java:76)
       at com.obscience.imamma.AbstractMainActivityPermissionsDispatcher.startBubbleServiceWithPermissionCheck(AbstractMainActivityPermissionsDispatcher.java:41)
       at com.obscience.imamma.AbstractMainActivity.startOrUpdateBubble(AbstractMainActivity.java:476)
       at com.obscience.imamma.AbstractMainActivity.onCreateMenu(AbstractMainActivity.java:466)
       at com.obscience.imamma.AbstractMainActivity$$Lambda$0.onClick(Unknown Source:4)
       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6590)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by hotchemi** [comment]
Seems Xiaomi doesn't support `SYSTEM_ALERT_WINDOW`? 🤔

**Comment by hotchemi** [comment]
@francescobonni if you don't use the library can you deal with the problem? 👀(thank you for your report and sorry for being late 🙇 )

**Comment by francescobonni** [comment]
No problem, I'm trying to find a Xiaomi MI A1 to perform the test without using the library and check if the problem is in the library or device. I will give you updates on the problem as soon as possible

**Comment by hotchemi** [comment]
any update?🙏

**Comment by hotchemi** [comment]
@francescobonni any update? 🙇

**Comment by francescobonni** [comment]
@hotchemi I'm sorry I had a lot of problems, but I found the device, this weekend I send you updates.

**Comment by francescobonni** [comment]
@hotchemi 
Finally I have updates, I tested with a clean application, the system overlay request and I found the behavior to replicate the crash on xiaomi mi a1 (now on Fabric i see same crash with redmi note 4 and android 6).
The crash occurs only if you use the library, step to reproduce the crash:
1) Activate the permission for the overlay through the app
2) I open the app information (eg through the launcher) and revoke the permission for the overlay
3) Return to the app and try to activate the permission again
4) Crash
5) Reopen app and retry to activate
6) Crash
7) Close app from recent
8) Open and retry to activate
9) Crash
10) I install the same app with manual permissions, everything works
11) I try in my Nexus 6P, everything works, both permission dispatcher and manual permissions

If you want I can put on my github the sample project I used, but it's very simple, a button that requires overlay permissions

**Comment by hotchemi** [comment]
@francescobonni oh it's happening on Android 6 as well..could you give us your sample project if possible? 🙇 Weird.. 👁

**Comment by francescobonni** [comment]
This is the [sample project](https://github.com/francescobonni/TestCrashPermissionsDispatcher-505)

I'm new on github, I did not know how to do things correctly, in the project at the moment you find 2 branches in addition to master (the first for the test without using the library and the second to test the library)

**Comment by hotchemi** [comment]
@francescobonni Thank you!

**Comment by francescobonni** [comment]
**News:

Device afflicted update: 

- Xiaomi Mi A1    (Android 8.1 & Android 8.0)
- Xiaomi Mi A2 Lite (Android 8.1)
- Xiaomi Redmi Note 4 (Android 6)

**Comment by hotchemi** [comment]
Sorry for the late. I think the cause is in https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/1564313f8b253685dc7189b0fbb31a42b2e86796/library/src/main/java/permissions/dispatcher/PermissionUtils.java#L95

May be we don't need to have a workaround for `SYSTEM_ALERT_WINDOW` 🤔 

@francescobonni Do you think the same thing would happen with `WRITE_SETTINGS`? 👀

**Comment by francescobonni** [comment]
@hotchemi this weekend I'll try the `WRITE_SETTINGS` and update you

**Comment by Denny966** [comment]
I guess you never tried it that weekend

**Comment by francescobonni** [comment]
Yes, I'm so sorry, but today I tried the write settings, same problem

**Comment by hotchemi** [comment]
ooh thank you. I'll address.

**Comment by hotchemi** [comment]
Let us know your opinion https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/544

**Comment by hotchemi** [comment]
Since we've already removed Xiaomi support from the lib let us close the issue.
@francescobonni thank you for your dedicated contribution 🙇 

ref: https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/548
