### ISSUE TITLE
Application getting crash on Pixel in Kotlin sample

### ISSUE THREAD

**Issue by onlymnsh** [permissions-dispatcher/PermissionsDispatcher#596]
Device:Google Pixel
OS Version: Android 9(Pie)

1)When click on camera  show error in Logs
W/CameraBase: An error occurred while connecting to camera 0: Status(-8): '1: validateClientPermissionsLocked:906: Caller "permissions.dispatcher.samplekotlin" (PID 10268, UID 27938) cannot open camera "0" without camera permission'

2) when click on Add a contact : App crash with follow logs
 Process: permissions.dispatcher.samplekotlin, PID: 27754
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{5ba2faa 27754:permissions.dispatcher.samplekotlin/u0a268} (pid=27754, uid=10268) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4185)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6019)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2573)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:1812)
        at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:1877)
        at android.content.ContentResolver.applyBatch(ContentResolver.java:1621)
        at permissions.dispatcher.samplekotlin.contacts.ContactsFragment.insertDummyContact(ContactsFragment.kt:124)
        at permissions.dispatcher.samplekotlin.contacts.ContactsFragment.access$insertDummyContact(ContactsFragment.kt:36)
        at permissions.dispatcher.samplekotlin.contacts.ContactsFragment$onViewCreated$2.onClick(ContactsFragment.kt:55)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12359)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:12651)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3297)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by hotchemi** [comment]
@onlymnsh Can you check permission is added in AndroidManifest or not? Seems the issue is related to do that.

https://stackoverflow.com/questions/26261769/w-camerabase-an-error-occurred-while-connecting-to-camera-0-on-camera-open-c

**Comment by hotchemi** [comment]
We haven't gotten enough info for the issue so let me close for the time being and reopen if needed 🙇
