### ISSUE TITLE
When this library is applied to Fragment and  run on Android 8.0, "System UI has stopped" is displayed.

### ISSUE THREAD

**Issue by kwmt** [permissions-dispatcher/PermissionsDispatcher#654]
## FAQs

 
___

## Overview

- When this library is applied to Fragment and  run on Android 8.0, "System UI has stopped" is displayed.

### Expected

- Works on Android 8.0

### Actual

- Doesn’t work on Android 8.0. 

## Environment

- Which library version are you using?
    - 4.5.0
- On which devices do you observe the issue?
    - Android8.0

- Note any other information that might be useful
    - The following versions will work:
        - 6.0.1
        - 7.0
        - 7.1.1
        - 8.1
        - 9.0
        - 10

## Reproducible steps
1. Ready on Android8.0 device ( What I saw was an emulator.)
2. Run the following branch.
https://github.com/kwmt/PermissionsDispatcher/tree/system-stop-on-fragment

This is a difference.
https://github.com/kwmt/PermissionsDispatcher/pull/1

**Comment by hotchemi** [comment]
Thx! In summary in Android 8.0 `Fragment#requestPermissions` has a bug and causes a crash? 👀 Let us check anyway 🙇

**Comment by hotchemi** [comment]
I've tried kwmt#1 with 8.0.0 emulator but somehow couldn't see the error. Could we get more detail or error message if possible? 🙇 @kwmt 

<img src="https://user-images.githubusercontent.com/471318/71823534-ca1b1e00-30da-11ea-8694-d420902a0078.gif" width="250" />

**Comment by kwmt** [comment]
Hi, @hotchemi 
Thank you for trying. It's a mystery 🤔 


-  The emulator I confirmed this problem is following image:
![image](https://user-images.githubusercontent.com/1450486/71955612-217cd380-322c-11ea-9498-1d074eed3cf4.png)
- As you can see, no error log.
![all_crash](https://user-images.githubusercontent.com/1450486/71956667-19726300-322f-11ea-97f6-2981518045fa.gif)

I hope this will help.

**Comment by hotchemi** [comment]
umm, thx let us check again! 🙇

**Comment by DreamerLeon** [comment]
@hotchemi 

In  PermissionsRequestFragment  onAttach Method 
`        activity?.requestedOrientation =
            if (context.resources.configuration.orientation == ORIENTATION_PORTRAIT)
                ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
            else
                ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE`


Android8.0 can't set orientation sometime ,Please fix this bug

Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.os.Parcel.readException(Parcel.java:1897)
        at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5760)
        at android.app.Activity.setRequestedOrientation(Activity.java:5793)
        at permissions.dispatcher.ktx.PermissionsRequestFragment.onAttach(PermissionsRequestFragment.kt:26)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:263)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1170)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at permissions.dispatcher.ktx.PermissionRequestType.requestPermissions$ktx_release(PermissionRequestType.kt:80)

**Comment by Moster1h** [comment]
I also encountered this problem, and the version used was 4.7.0.
