### ISSUE TITLE
Kotlin 1.7 Support

### ISSUE THREAD

**Issue by chenxiangcxc** [permissions-dispatcher/PermissionsDispatcher#775]
We are trying to upgrade project code to Kotlin 1.7 however PermissionsDispatcher blocks us as it only supports Kotlin 1.5.
Is there any plan to support Kotlin 1.7? Below is the error:

```
Caused by: java.lang.IllegalArgumentException: Modifiers [PRIVATE] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]
	at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:41)
	at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:29)
	at com.squareup.kotlinpoet.ParameterSpec$Builder.build(ParameterSpec.kt:157)
	at com.squareup.kotlinpoet.FunSpec$Builder.addParameter(FunSpec.kt:500)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createPermissionRequestClass(KotlinBaseProcessorUnit.kt:452)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createPermissionRequestClasses(KotlinBaseProcessorUnit.kt:415)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createFile(KotlinBaseProcessorUnit.kt:43)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createFile(KotlinBaseProcessorUnit.kt:17)
	at permissions.dispatcher.processor.PermissionsProcessor.processKotlin(PermissionsProcessor.kt:68)
	at permissions.dispatcher.processor.PermissionsProcessor.process(PermissionsProcessor.kt:58)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)

```

**Comment by tommyjackson** [comment]
We're using Kotlin 1.7.10 with version 4.9.2 of this library and haven't ran into any issues.

**Comment by carterhudson** [comment]
But the latest version is 4.8.0... Are you using a snapshot or something?

**Comment by tommyjackson** [comment]
@carterhudson the Github Releases look like they just haven't been updated. The [installation](https://github.com/permissions-dispatcher/PermissionsDispatcher#installation) section of the readme says
> ${latest.version} is maven central 4.9.2

with a link to the releases on maven central

**Comment by carterhudson** [comment]
Gotcha. It doesn't resolve for me, for some reason.

Edit: ah, package changed.

**Comment by carterhudson** [comment]
I'm still having the issue when using 4.9.2. It seems like it's due to `KModifier.PRIVATE` being used [here](https://github.com/permissions-dispatcher/PermissionsDispatcher/search?q=KModifier.PRIVATE)? It's strange, though. It only happens when I try to depend on a certain different dependency.

**Comment by carterhudson** [comment]
Looks like using Showkase forces the dependency to 1.12.0 where this lib uses 1.[0]3.0?

**Comment by ubarua123** [comment]
Any updates on this? i am kinda stuck at this point here and 4.9.2 doesn't seem to solve it

**Comment by carterhudson** [comment]
I have a pr up that fixed it for me in a fork, but this repo seems to be
slightly unmaintained.

**Comment by ubarua123** [comment]
@carterhudson can you paste the link of your fork? I'll download it, Yeah it looks like this library is unmaintained.

**Comment by carterhudson** [comment]
> @carterhudson can you paste the link of your fork? I'll download it, Yeah it looks like this library is unmaintained.

https://github.com/carterhudson/PermissionsDispatcher

**Comment by ubarua123** [comment]
Well, the best alternative is, use the `com.github.permissions-dispatcher:permissionsdispatcher-ktx` version of the library. Works perfect and without the need of annotations.
