### ISSUE TITLE
kotlin 1.8 Modifiers [PRIVATE] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]

### ISSUE THREAD

**Issue by akingyin1987** [permissions-dispatcher/PermissionsDispatcher#779]
version:4.9.2
Caused by: java.lang.IllegalArgumentException: Modifiers [PRIVATE] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]
	at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:41)
	at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:29)
	at com.squareup.kotlinpoet.ParameterSpec$Builder.build(ParameterSpec.kt:157)
	at com.squareup.kotlinpoet.FunSpec$Builder.addParameter(FunSpec.kt:465)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createPermissionRequestClass(KotlinBaseProcessorUnit.kt:452)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createPermissionRequestClasses(KotlinBaseProcessorUnit.kt:415)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createFile(KotlinBaseProcessorUnit.kt:43)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createFile(KotlinBaseProcessorUnit.kt:17)
	at permissions.dispatcher.processor.PermissionsProcessor.processKotlin(PermissionsProcessor.kt:68)
	at permissions.dispatcher.processor.PermissionsProcessor.process(PermissionsProcessor.kt:58)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
	... 44 more

**Comment by akingyin1987** [comment]
if google dagger2 version is 2.4.5

**Comment by kassim** [comment]
I'm receiving this error as well

seems to be the same issue as https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/775

**Comment by minwonki** [comment]
I too have the same problem.
kotlin version : 1.8.10
permissionsdispatcher version : 4.9.2

Caused by: java.lang.IllegalArgumentException: Modifiers [PRIVATE] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]
	at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:41)
	at com.squareup.kotlinpoet.ParameterSpec.<init>(ParameterSpec.kt:29)
	at com.squareup.kotlinpoet.ParameterSpec$Builder.build(ParameterSpec.kt:157)
	at com.squareup.kotlinpoet.FunSpec$Builder.addParameter(FunSpec.kt:465)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createPermissionRequestClass(KotlinBaseProcessorUnit.kt:452)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createPermissionRequestClasses(KotlinBaseProcessorUnit.kt:415)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createFile(KotlinBaseProcessorUnit.kt:43)
	at permissions.dispatcher.processor.impl.kotlin.KotlinBaseProcessorUnit.createFile(KotlinBaseProcessorUnit.kt:17)
	at permissions.dispatcher.processor.PermissionsProcessor.processKotlin(PermissionsProcessor.kt:68)
	at permissions.dispatcher.processor.PermissionsProcessor.process(PermissionsProcessor.kt:58)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:985)
	... 44 more

**Comment by kassim** [comment]
I believe I used this workaround
https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/775#issuecomment-1324573825
 (use `com.github.permissions-dispatcher:permissionsdispatcher-ktx` instead of the normal annotation version)

**Comment by shaomaicheng** [comment]
I find reason for this issus,and i create a pr for this: https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/782
